---
title: "Indice tentativo"
output: github_document
---

Este archivo recojera lo que se me ocurra para introducirlo al repositorio. Por el momento puede ser general y muy poco informativos, esto a causa de la finalidad de este repositorio es la perdida de miedo al lenguaje de programacion y al uso de intrumentos, los cuales estan disponibles para otros lenguajes de programacion. 

Por otra parte, este repositorio tratara de enfocarse en el uso y manejo de datos asi como la visualizacion (y puede que talvez algo de estimaciones estadisticas y econometricas) y comunicacion de este, por lo que se omite partes importantes de los otros usos que puede tener este lenguaje de programacion.



## General 

- Introduccion a Rstudio 

- Introduccion a R-base

- Introduccion a Tidyverse 

- Variables y objetos

## Tidyverse 

El concepto de `tidy data`, o datos limpios los cuales ya no requieren mayor manipulacion y poder pasar al modelamiento y/o visualizacion de resultados.

- Importar y exportar datos

- Visualizar (I)

- Manipulacion  
